### ISSUE TITLE
Fixes for submission as Expo Router example

### ISSUE THREAD

**Issue by karlhorky** [hola-soy-milk/upleveled-react-native-expo#2]
Hi @hola-soy-milk 👋

Just tried submitting this repo as another example for Expo Router over here:

- https://github.com/expo/router/pull/332

However Evan [mentioned](https://github.com/expo/router/pull/332#issuecomment-1448885895) that there were a few things that should be fixed:

- app.json is invalid [hola-soy-milk/upleveled-react-native-expo@c884c9c/guest-list-mobile/app.json#L5](https://github.com/hola-soy-milk/upleveled-react-native-expo/blob/c884c9c432e18f6be5212dd484610fa168117840/guest-list-mobile/app.json#L5)
- button is clipped by notch
- App.tsx is extranous
- example isn't using Layout routes, instead opting to use a custom header component.

Maybe you can fix those up and reply over there?

**Comment by hola-soy-milk** [comment]
Fixes made and submitted to Evan again

**Comment by karlhorky** [comment]
Great, thanks!
